config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :users, only: [:show, :edit, :update]
  resources :organizations do
    resources :events, except: [ :index, :show]
    resources :reviews, only: [:index ]
  end
  resources :events, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, except: [:show, :new, :create] do
    resources :reviews, only: [:new, :create]
    member do
      post 'approve', to: 'bookings#approve'
      post 'reject', to:'bookings#reject'
    end
  end
  # resources :reviews, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :organizations
  has_many :bookings

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, except: [:update]

  def show
    authorize @user
    @booking =
    @review = Review.new
    @bookings = Booking.where(user: @user)
    @organization = Organization.where(user_id:current_user.id).first
    @completed_bookings = @bookings.where(status:"Completed")
    @confirmed_bookings = @bookings.where(status:"Confirmed")
    @pending_bookings = @bookings.where(status:"Pending")
    @cancelled_bookings = @bookings.where(status:"Cancelled")
    @rejected_bookings = @bookings.where(status:"Rejected")
    @card_color = {"Confirmed" => "bg-success", "Pending" => "bg-warning", "Rejected" => "bg-danger", "Completed" => "bg-info", "Cancelled" => "text-dark bg-light"}
  end

  def edit
    authorize @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_booking.html.erb
<% if bookings.present? %>
  <div class='col-lg-12 col-md-12 col-sm-12'>
    <h3 class="text-center mt-4 text-white shadow p-3 mb-5 rounded <%= @card_color[bookings.first.status.capitalize] %> " style="opacity: .5;""><%= bookings.first.status.capitalize  %></h3>

    <% bookings.each do |booking| %>
      <div class="row mt-4 text-white shadow p-3 mb-5 rounded text-dark bg-light ">
        <div class="col col-lg-3   mt-3">
          <h3 class="mb-0 "><%= link_to booking.event.title, booking.event %></h3>
        </div>
        <div class="col col-lg-3 mt-3">
          <p><img src="https://res.cloudinary.com/dj1bs7vyp/image/upload/v1559562074/starttime_bgwtqv.png" class="icon-size"> <%= booking.event.start_at.to_formatted_s(:long_ordinal) %></p>
          <p><img src="https://res.cloudinary.com/dj1bs7vyp/image/upload/v1559562048/endtime_u2gchd.png" class="icon-size"> <%= booking.event.ends_at.to_formatted_s(:long_ordinal) %></p>
          <!-- other datetime formats here https://api.rubyonrails.org/classes/DateTime.html -->
        </div>
        <div class="col col-lg-3   mt-3">
          <p><i class="fas fa-map-pin"></i> <%= booking.event.address %></p>
        </div>
        <div class="col col-lg-3   mt-3">
          <p>
            <i class="fas fa-users"></i> <%= booking.event.spots %>
            <% if booking.status == "Completed" %>
              <% if !Review.where(booking_id:booking.id).any? %>
              <a class="btn btn-completed float-right text-white" data-toggle="modal" data-target="#createreview">Write Review</a>
              <% else %>
                <p style="color:grey;">You already submitted a review. Thank you!</p>
              <% end %>
              <% elsif booking.status == "Pending" %>
              <%= link_to 'Cancel Booking', booking_path(booking), data: {:confirm => 'Are you sure?'}, method: :delete, class:'btn bg-danger float-right text-white' %>
            <% end %>
          </p>
        </div>

      </div>
    <% end %>
  </div>
<% end %>

<div class="modal fade bd-example-modal-lg" id="createreview" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="my-forms">
        <div class="container p-5">
          <h5 class="pt-4 pb-2 text-center" style="color:grey;">How was the event? Add a review, <%= current_user.first_name %>!</h5>
          <%= simple_form_for [@completed_bookings.first, @review], html: {class:'text-center'} do |f| %>
              <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", label_html: { class: "d-block" } %>
            <%= f.input :content, label_html: {class:'pt-4'}  %>
            <%= f.submit "Submit a review", class:"btn btn-sm btn-event-index" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container" style="<%= @bookings.empty? || @user != current_user ? 'min-height: 95vh' : '' %>">
    <div class="panel-heading">
       <h3 class="py-2 text-center" style="color:grey;"><%= @user.first_name %> <%= @user.last_name %></h3>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6  toppad" >
        <%= image_tag @user.photo, :class => "profile-image" %>
        <% if policy(@user).edit? %>
          <p class="text-center pt-2"><%= link_to "Edit profile", edit_user_registration_path, id:"link-organization", class:"ml-2"%></p>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6  toppad" >


        <div class="panel panel-info">

          <div class="panel-body">
            <div class="row">
              <div class="text-left card-event-show col-lg-10 col-md-6 col-sm-12">
                <table class="table table-user-information">
                  <tbody>
                    <tr>
                      <td><i class="fas fa-calendar"></i></td>
                      <td><%= Time.zone.now.year - @user.dob.year %></td>
                    </tr>
                    <tr>
                      <td><i class="fas fa-map-pin"></i></td>
                      <td><%= @user.city %></td>
                    </tr>
                    <tr>
                      <td><i class="far fa-envelope"></i></td>
                      <td><%= @user.email %></td>
                    </tr>
                    <tr>
                     <tr>
                      <td><i class="fas fa-phone"></i></td>
                      <td><%= @user.phone %></td>
                    </tr>
                    <tr>
                      <td><i class="fas fa-heart"></i></td>
                      <td><%= @user.interests %></td>
                    </tr>
                    <tr>
                      <td><i class="far fa-comment-alt"></i></td>
                      <td><%= @user.bio %></td>
                    </tr>
                  </tr>
                </tbody>
              </table>
              <% if current_user == @user %>
              <table>
                <tbody>
                  <tr>
                    <td class="ml-2">
                      <p><%= link_to "Do Good", events_path, class:"btn btn-success float-center" %></p>

                    </td>
                    <td>
                      <% if Organization.where(user:current_user).present? %>
                      <p><%= link_to "Go to Organization", organization_path(@organization), class:"btn-organization-shows ml-2"%></p>
                      <% else %>
                      <p><%= link_to "Create organization", new_organization_path, class:"btn-organization-show ml-2" %></p>
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @user == current_user %>
    <div class="container mt-0">
      <h3 class="py-2 text-center" style="color:grey;">My Bookings</h3>
      <% if @bookings.empty? %>
        <div class="row card-background mt-4">
          <p>No Bookings yet</p>
        </div>
      <% end %>
      <%= render 'users/booking', bookings: @completed_bookings %>
      <%= render 'users/booking', bookings: @confirmed_bookings %>
      <%= render 'users/booking', bookings: @pending_bookings %>
      <%= render 'users/booking', bookings: @cancelled_bookings %>
      <%= render 'users/booking', bookings: @rejected_bookings %>
    </div>
  <% end %>
</div>