config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :users, only: [:show, :edit, :update]
  resources :organizations do
    resources :events, except: [ :index, :show]
    resources :reviews, only: [:index ]
  end
  resources :events, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, except: [:show, :new, :create] do
    resources :reviews, only: [:new, :create]
    member do
      post 'approve', to: 'bookings#approve'
      post 'reject', to:'bookings#reject'
    end
  end
  # resources :reviews, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization
  has_many :bookings
  geocoded_by :address
  validates :start_at, :ends_at, :address, :task, :title, :spots, :category, presence: true
  after_validation :geocode, if: :will_save_change_to_address?

  scope :date_between, ->(start_date, end_date) { where(start_at: start_date..end_date) }

include PgSearch
  pg_search_scope :search_by_title_and_task_and_description_and_category,
    against: [:title, :task, :description, :category],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  pg_search_scope :search_by_category,
    against: [:category],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def category_icon(category)
    if category == "Animal"
      "<i class='fas fa-paw' style='color:brown'></i>"
    elsif category == "Environment"
      "<i class='fas fa-leaf' style='color:green'></i>"
    elsif category == "Community"
      "<i class='fas fa-hands-helping' style='color:grey'></i>"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = policy_scope(Event).order(created_at: :desc)

    if params[:query].present?
      @events = @events.search_by_title_and_task_and_description_and_category(params[:query])
    end

    if params[:date].present?
      start_date, end_date = params[:date].split(' - ')

      @events = @events.date_between(start_date, end_date)
    end

    if params[:category].present?
      @events = @events.search_by_title_and_task_and_description_and_category(params[:category])
    end

    @markers = @events.map do |event|
      if event.category == "Animal"
        category_image = helpers.asset_url('paw-solid.svg')
      elsif event.category == "Environment"
        category_image = helpers.asset_url('leaf-solid.svg')
      elsif event.category == "Community"
        category_image = helpers.asset_url('hands-helping-solid.svg')
      end
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { event: event }),
        image_url: category_image
      }
    end
  end

  def show
    authorize @event
    @bookings = Booking.where(event:@event)
    @organization = @event.organization
  end

  def new
    @organization = Organization.find(params[:organization_id])
    @user = current_user
    @event = Event.new
    @event.organization = @organization
    authorize @event
  end

  def create
    @event = Event.create(event_params)
    @user = current_user
    @organization = Organization.find(params[:organization_id])
    @event.organization = @organization
    authorize @event
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def edit
    @organization = @event.organization
    @user = current_user
    authorize @event
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event.delete
    authorize @event
    @organization = Organization.find(params[:organization_id])
    redirect_to @organization
  end

  private

  def event_params
    params.require(:event).permit(:start_at, :ends_at, :address, :task, :title, :spots, :category, :description, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_infowindow.html.erb
<h2><%= event.title %></h2>
        <p><i class="fas fa-map-marker-alt"></i> <%= event.address %></p>
        <%= link_to "More Information", event, class:"btn btn-sm btn-event-index" %>
        </button>

app/views/events/edit.html.erb
<div class="my-forms my-4">
  <div class="container w-50 py-3 purple-gradient color-block" id="form-container">
    <h5 class="text-center">Edit event</h5>
    <%= link_to "<< Go back to the organization", @organization, id:'link-organization' %>
    <%= simple_form_for [@organization, @event] do |f| %>
      <%= f.input :title, label_html: {class:'pt-1'} %>
      <%= f.input :start_at, as: :datetime %>
      <%= f.input :ends_at, label_html: {class:'pt-1'} %>
      <%= f.input :address, label_html: {class:'pt-1'} %>
      <%= f.input :task, label_html: {class:'pt-1'} %>
      <%= f.input :description, label_html: {class:'pt-1'} %>
      <%= f.input :spots, label_html: {class:'pt-1'} %>
      <%= f.input :category, collection: Organization::CATEGORIES, label_html: { class:'pt-1'} %>
       <%= f.file_field :photo, label_html: {class:'pt-2'} %>
      <%#= f.input :photo_cache, as: :hidden %>
      <div class="text-center">
        <%= f.submit "Update event", class: "btn btn-primary mb-5" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<div class="flexbox-container">
  <h3 class="pt-4 pb-2 text-center" style="color:grey;">Upcoming Events</h3>
</div>
<div class="d-flex border-bottom justify-content-center">
  <% if policy(@events).index? %>
    <div class="ui compact menu my-auto">
      <div class="ui simple dropdown item">
        Category
        <i class="dropdown icon"></i>
        <div class="menu">
          <div class="item"><%= link_to "Environment", category: "Environment" %></div>
          <div class="item"><%= link_to "Animal", category: "Animal" %></div>
          <div class="item"><%= link_to "Community", category: "Community" %></div>
        </div>
      </div>
    </div>
    <%= form_tag events_path, id: "event-form",method: :get do %>
      <div class="index-search">
        <span class="fas fa-search"></span>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          style: "margin-right: 20px;",
          placeholder: "Find the perfect event"
        %>
      </div>
      <%= text_field_tag :date, params[:date], class: "form-control", data: { behavior: 'daterangepicker' } %>
      <%= submit_tag :search, class: "btn btn-event-index" %>
    <% end %>
  <% end %>
</div>

<div class="index-container">
  <div class="events-index-grid">
    <div class ="cards mr-3">
    <% @events.each do |event| %>
    <div class="container event-index-card mb-3">
      <div class="row">
        <div class="col", style="flex-grow:0">
          <%= cl_image_tag(event.photo, class:"card-image") %>
        </div>
        <div class="col">
          <p class="small card-text mb-0">
            <%= event.title %><span class="float-right mt-1"><i class="fas fa-user"></i> <%= event.spots %></span>
          </p>
            <div>
              <p class="small card-text mb-0">
                <%= link_to event.organization.name, event.organization %>
              </p>
              <p class="small card-text mb-0">
                <img src="https://res.cloudinary.com/dj1bs7vyp/image/upload/v1559562074/starttime_bgwtqv.png" class="icon-size"> <%= event.start_at.to_formatted_s(:short) %> - <%= event.ends_at.to_formatted_s(:short) %>
              </p>
              <%= link_to "More Information", event, class:"btn btn-sm btn-event-index mt-4" %>
            </div>
        </div>
        <div class="col-lg-1">
          <%#= event.category_icon.html_safe %>
          <%= event.category_icon(event.category).html_safe %>
        </div>

    </div>
      </div>
    <% end %>
    </div>
    <div
      id="map"
      style="width: 100%;
      height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY']%>">
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="my-forms my-4">
  <div class="container py-3 purple-gradient color-block">
    <h5 class="text-center">Create an event</h5>
      <%= link_to "Go back to the organization", @organization, id:'link-organization' %>
      <%= simple_form_for([@organization, Event.new], url: organization_events_path(@organization)) do |f| %>
      <%= f.input :title, label_html: {class:'pt-1'} %>
      <%= f.input :start_at, as: :datetime%>
      <%= f.input :ends_at, label_html: {class:'pt-1'} %>
      <%= f.input :address, label_html: {class:'pt-1'} %>
      <%= f.input :task, label_html: {class:'pt-1'} %>
      <%= f.input :description, label_html: {class:'pt-1'} %>
      <%= f.input :spots, label_html: {class:'pt-1'} %>
      <%= f.input :category, collection: Organization::CATEGORIES, label_html: { class:'pt-1'} %>
       <%= f.file_field :photo, label_html: {class:'pt-2'} %>
      <%#= f.input :photo_cache, as: :hidden %>
    <div class="text-center">
      <%= f.submit "Create event", class: "btn btn-primary mb-5" %>
    </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container" style="min-height:100vh;">
  <h3 class=" text-center my-3" style="color:grey;"><%= @event.title %></h3>
  <div class="events-index-grid">
    <div class="col-lg-12 col-md-12 col-sm-12 text-center px-0">
      <%= cl_image_tag @event.photo, class:'event-show-img'%>
    </div>
    <div class="card-event-show col-lg-10 col-md-6 col-sm-12">
      <div class="row">
        <div class="col-1 mb-2"><p><i class="fas fa-home"></i></p></div>
        <div class="col-11 mb-2"><%=link_to @event.organization.name, organization_path(@event.organization), id:"link-organization"  %></div>
        <div class="col-1 mb-2"><i class="fas fa-map-pin"></i></div>
        <div class="col-11 mb-2"><%= @event.address %></div>
        <div class="col-1 mb-2"><img src="https://res.cloudinary.com/dj1bs7vyp/image/upload/v1559562074/starttime_bgwtqv.png" class="icon-size"></div>
        <div class="col-11 mb-2"><%= @event.start_at.to_formatted_s(:long_ordinal) %></div>
        <div class="col-1 mb-2"><img src="https://res.cloudinary.com/dj1bs7vyp/image/upload/v1559562048/endtime_u2gchd.png" class="icon-size"></div>
        <div class="col-11 mb-2"><%= @event.ends_at.to_formatted_s(:long_ordinal) %></div>
        <div class="col-1 mb-2"><i class="fas fa-users"></i></div>
        <div class="col-11 mb-2">
          <% size = 0  %>
          <% @bookings.each do |booking| %>
            <% if booking.status == "Confirmed"  %>
              <% size += 1 %>
            <% end %>
          <% end  %>
            <%= size %>
            /<%= @event.spots %> spots taken</div>
        <div class="col-1 mb-2"><i class="far fa-comment-alt"></i></div>
        <div class="col-11 mb-2"><%=h truncate(@event.description, :length => 180) %></div>
        <div class="col-1 mb-2"><p><i class="fas fa-tasks"></i></p></div>
        <div class="col-11 mb-2"><%=h truncate(@event.task, :length => 80) %></div>
        <div class="col-11 mb-2"></div>
      </div>
      <% if @event.organization.user != current_user %>
        <% if @bookings.where(user:current_user).any? %>
          <button type="disabled">Applied</button>
        <% else %>
          <%= link_to "Apply now", event_bookings_path(@event), method: :post, class:"btn btn-success" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="mt-2 pl-5" id='link-organization'>
    <% if current_user == @event.organization.user %>
      <p><%= link_to "Edit event", edit_organization_event_path(@organization, @event), id:"link-organization" %> |
      <%= link_to "Delete event", organization_event_path(@organization, @event), method: :delete, confirm: "Are you sure?",class:"text-danger", id:'link-organization' %></p>
    <% end %>
  </div>
    <% if @event.organization.user == current_user %>
      <% if @bookings.empty? %>
        <div class=" card-background">
        <p>No Bookings yet</p>
      <% else %>
        <div><h2 class="text-center mb-5" style="color:grey;">Bookings</h2>
          <div>
            <div class='list-group'>
              <% @bookings.each do |booking| %>
                <div class="list-group-item mb-2">
                  <div class="row">
                    <div class="col-3">
                      <p> <%= link_to booking.user.fullname , user_path(booking.user) %></p>
                    </div>
                    <div class="col-3">
                      <p>Status: <strong><%= booking.status %></strong></p>
                    </div>
                    <% if booking.status == "Pending" %>
                      <div class="col-3">
                        <%= link_to 'Confirm', approve_booking_path(booking, event_id:@event.id), method: :post, class:"btn btn-confirm" %>
                      </div>
                      <div class="col-3">
                        <%= link_to 'Reject', reject_booking_path(booking, event_id:@event.id), method: :post, class:"btn btn-reject" %>
                      </div>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<p class="small mb-0 ml-5">Some icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"        title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"        title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></p>