config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { sessions: 'sessions' }

  resources :users, only: [:show, :edit, :update]
  resources :organizations do
    resources :events, except: [ :index, :show]
    resources :reviews, only: [:index ]
  end
  resources :events, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, except: [:show, :new, :create] do
    resources :reviews, only: [:new, :create]
    member do
      post 'approve', to: 'bookings#approve'
      post 'reject', to:'bookings#reject'
    end
  end
  # resources :reviews, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :bookings, through: :events
  has_many :reviews, through: :bookings
  validates :name, :address, :category, :url, :description, presence: true
  mount_uploader :photo_url, PhotoUploader

  CATEGORIES = %w( Animal Environment Community)

  def category_icon(category)
    if category == "Animals"
      "<i class='fas fa-paw' style='color:brown'></i>"
    elsif category == "Environment"
      "<i class='fas fa-leaf' style='color:green'></i>"
    elsif category == "Community"
      "<i class='fas fa-hands-helping'></i>"
    end
  end
end

# add validations for default value of :verified. Should it be boolean?
# add validations for default lengths of each string/text field

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  def index
    @organizations = policy_scope(Organization).order(created_at: :desc)
  end

  def show
    @user = @organization.user
    @reviews = @organization.reviews
    authorize @organization
    authorize @user
    @events = Event.where(organization_id:@organization.id)
    @bookings = Booking.where(event:@event)
  end

  def new
    @organization = Organization.new
    authorize @organization
  end

  def create
    @organization = Organization.create(organization_params)
    @organization.user = current_user
    authorize @organization
    if @organization.save
      redirect_to @organization
    else
      render :new
    end
  end

  def edit
    authorize @organization
  end

  def update
    @organization.update(organization_params)
    authorize @organization
    if @organization.update(organization_params)
      redirect_to @organization
    else
      render :edit
    end
  end

  def destroy
    @organization.delete
    authorize @organization
    redirect_to current_user
  end

  private

  def organization_params
    params.require(:organization).permit(:name, :address, :category, :url, :description, :photo_url)
  end

  def set_organization
    @organization = Organization.find(params[:id])
  end
end

app/views/organizations/edit.html.erb
<div class="my-forms my-4">
  <div class="container py-3 purple-gradient color-block">
    <h5 class="text-center">Edit Organization info</h5>
    <%= simple_form_for [@organization] do |f| %>
      <%= f.input :name, label_html: {class:'pt-4'} %>
      <%= f.input :address, label_html: {class:'pt-1'} %>
      <%= f.input :description, label_html: {class:'pt-1'} %>
      <%= f.input :url, label_html: {class:'pt-1'} %>
      <%= f.input :category, collection: Organization::CATEGORIES, label_html: { class:'pt-1'} %>
       <%= f.file_field :photo_url, label_html: {class:'pt-2'} %>
      <%= f.input :photo_url_cache, as: :hidden %>
    </div>
    <div class="text-center">
      <%= f.submit "Update Organization", class: "btn btn-primary mb-5" %>
    <% end %>
    </div>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="my-forms my-4">
  <div class="container py-3 purple-gradient color-block">
    <h5 class="text-center">Create Organization</h5>
    <%= simple_form_for [@organization] do |f| %>
      <%= f.input :name, label_html: {class:'pt-4'} %>
      <%= f.input :address, label_html: {class:'pt-1'} %>
      <%= f.input :description, label_html: {class:'pt-1'} %>
      <%= f.input :url, label_html: {class:'pt-1'} %>
      <%= f.input :category, collection: Organization::CATEGORIES, label_html: { class:'pt-1'} %>
       <%= f.file_field :photo_url, label_html: {class:'pt-2'} %>
      <%= f.input :photo_url_cache, as: :hidden %>
    </div>
    <div class="text-center">
      <%= f.submit "Create Organization", class:"btn btn-sm btn-event-index" %>
    <% end %>
    </div>
  </div>
</div>

app/views/organizations/show.html.erb
<div class="container" style="height:100vh;">
  <div class="card" id="organization-show">
    <div class="col text-center">
      <h2><%= @organization.name %>
        <%= @organization.category_icon(@organization.category).html_safe %> </h2>
    </div>

    <div class="col text-center pb-3">
      <% if !@reviews.empty? %>
          <% sum = 0.0  %>
          <% @reviews.each do |review| %>
          <% sum += review.rating %>
          <% end %>
          <% average = sum / @reviews.size %>
          <% stars = average.to_i %>
          <% stars.times do %>
          <i class="fas fa-star"></i>
          <% end %>
          (<%= average.round(2) %>)
          | <a href='#' class="text-primary" data-toggle="modal" data-target="#reviews">
            <% if @reviews.size == 1 %>
              <%= @reviews.size %> review
            <% else %>
              <%= @reviews.size %> reviews
            <% end %>
          </a>
    </div>

    <!-- Modal -->
    <div class="modal fade bd-example-modal-lg" id="reviews" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title text-center" id="exampleModalLabel">Reviews of <%= @organization.name %></h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body list-group">
            <% @reviews.each do |review| %>
            <div class="list-group-item">
              <div class="rating-review-flexbox">
                <p>
                <% review.rating.times do %>
                <i class="fas fa-star"></i>
                <% end %>

                <% (5 - review.rating).times do %>
                <i class="far fa-star"></i>
                <% end %>
                </p>
                <p style="color:grey; font-style:italic;">by <%= review.booking.user.fullname %></p>
              </div>
              <p><%= review.content %></p>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>

    <div class="col text-center pb-3">Organized by <% if policy(User).show? %>
      <%= link_to @organization.user.fullname, user_path(@organization.user), id:'link-organization' %>
      <% end %>
    </div>

  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6  toppad" >
      <%= cl_image_tag(@organization.photo_url, class:"profile-image") %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 text-left toppad" >
          <div class="panel panel-info">

            <div class="panel-body">
              <div class="row">
                <div class=" col-md-12 col-lg-12 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td><i class="fas fa-map-pin"></i></td>
                        <td><%= @organization.address %></td>
                      </tr>
                      <tr>
                        <td><i class="fas fa-external-link-alt"></i></td>
                        <td><%= @organization.url %></td>
                      </tr>
                      <tr>
                       <tr>
                        <td><i class="fas fa-phone"></i></td>
                        <td><%= @organization.user.phone %></td>
                      </tr>
                      <tr>
                        <td><i class="far fa-envelope"></i></td>
                        <td><%= @organization.user.email %></td>
                      </tr>
                      <tr>
                        <td><i class="far fa-comment-alt"></i></td>
                        <td><%= @organization.description %></td>
                      </tr>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% if @organization.user == current_user %>
      <div class="col-lg-12">

        <div class="row organization-show-links">
          <div class=" col text-center ml-5">
          <p><%= link_to "Edit organization", edit_organization_path(@organization), id:'link-organization' %> | <%= link_to "Delete organization", organization_path(@organization), data: {:confirm => 'Are you sure?'}, method: :delete, id:'link-organization' %></p>
          </div>
          <div class="col"></div>
          <%= link_to "Create a new event", new_organization_event_path(@organization), class:'btn btn-lg btn-event-index mr-4 mb-5' %>
        </div>

      </div>
    <% end %>
  </div>
  </div>
</div>

<div class="card" id="organization-show">
  <% if @organization.events.empty? %>
    <h3 class="text-left mt-2">No Upcoming Events</h3>
  <% else %>

    <div>
      <h2 class="text-center mt-2">Upcoming events:</h2>
    </div>

    <div class="container">

        <div class="row">
          <% @events.each do |event| %>
          <div class="col-4">
            <div class="card">
              <div class="overlay-image">
                <img class="image" src=<%= event.photo %> alt="Event Photo" />
                <div class="text">
                  <%= @organization.category_icon(@organization.category).html_safe %>

                </div>
              </div>
              <!-- <img class="card-img-top" src=<%= event.photo %> alt="Card image cap"> -->
              <div class="card-body d-flex flex-column">
                <h3 class="card-title">
                  <%= event.title %>

                </h3>

                <span>
                  <i class="fas fa-users"></i> <%= rand(1..event.spots) %>/<%= event.spots %>
                </span>

                <p class="card-text">
                <img src="https://res.cloudinary.com/dj1bs7vyp/image/upload/v1559562074/starttime_bgwtqv.png" class="icon-size">
                <%= event.start_at.to_formatted_s(:short) %>
                 -
                <%= event.ends_at.to_formatted_s(:short) %>
                </p>


                <p>
                  <%=h truncate(event.description, :length => 80) %>
                </p>
                <div class="align-self-end mt-auto">
                    <%= link_to "More Info", event, class:"btn-organization-show" %>
                </div>
              </div>
            </div>
          </div>
          <% end %>

         </div>

     </div>
  <% end %>
  </div>